### ISSUE TITLE
sbt eclipse generates module1 project which has error

### ISSUE THREAD

**Issue by caiiiycuk** [xitrum-framework/xitrum-multimodule-demo#5]
How to reproduce:
* git clone https://github.com/xitrum-framework/xitrum-multimodule-demo.git
* sbt eclipse
* open in eclipse

There are error in module1 project:
Project 'module1' is missing required library: '../module1/config'	module1		Build path	Build Path Problem

How to fix:
* mkdir -p module1/config
* refresh project

**Comment by ngocdaothanh** [comment]
I was thinking about removing "config" directory from module1, so that only the main app contains the config.

What do you think?

**Comment by caiiiycuk** [comment]
I think that this is best approach. In our company we add "config" to
classpaths only for submodules that are webapps. I mean we have one big
project to share a code. Many of subprojects are webapps, other projects
are lib projects.

2015-04-27 15:24 GMT+07:00 Ngoc Dao <notifications@github.com>:

> I was thinking about removing "config" directory from module1, so that
> only the main app contains the config.
>
> What do you think?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xitrum-framework/xitrum-multimodule-demo/issues/5#issuecomment-96555142>
> .
>



-- 
С уважением, Гурьянов Александр

**Comment by ngocdaothanh** [comment]
I've made the fix.
Thanks Aleksander for the feedback :+1:
